package reconciliation.rule

import darpan.common.DarpanEntityConstants
import darpan.facade.common.TenantScopedFinder
import org.kie.api.KieServices
import org.kie.api.builder.KieBuilder
import org.kie.api.builder.KieFileSystem
import org.kie.api.builder.Message
import org.kie.api.runtime.KieContainer
import org.kie.api.runtime.KieSession
import org.moqui.entity.EntityValue
import org.slf4j.Logger
import org.slf4j.LoggerFactory

import java.security.MessageDigest
import java.util.Locale
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.ConcurrentMap

import static darpan.common.ValueSupport.normalize
import static darpan.common.ValueSupport.sanitizeDisplayName
import static reconciliation.rule.RuleConditionParser.parseCondition

class RuleEngineSupport {
    private static final int MAX_ID_LENGTH = 60
    private static final Logger logger = LoggerFactory.getLogger(RuleEngineSupport.class)
    private static final Set<String> JAVA_KEYWORDS = [
            "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class", "const",
            "continue", "default", "do", "double", "else", "enum", "extends", "final", "finally", "float",
            "for", "goto", "if", "implements", "import", "instanceof", "int", "interface", "long", "native",
            "new", "package", "private", "protected", "public", "return", "short", "static", "strictfp",
            "super", "switch", "synchronized", "this", "throw", "throws", "transient", "try", "void",
            "volatile", "while"
    ] as Set<String>

    // Audit H9.16 — RULESET_CACHE was previously an unbounded ConcurrentHashMap that leaked Drools
    // KieContainer instances (each holds a classloader + generated bytecode + KBase + KieModule).
    // Edit-then-recompile churn — common during rule authoring — accumulated containers in Metaspace
    // for hours until the JVM died. Now an LRU keyed on (tenantId, ruleSetId) with a hard cap and
    // explicit KieContainer.dispose() on eviction. Override the cap via the
    // 'darpan.reconciliation.rule.cacheMax' resource property if a tenant needs more concurrent
    // compiled rulesets cached.
    static final int DEFAULT_RULESET_CACHE_MAX = 200

    // Self-review pen-test: a tenant rule consequence can call update()/modify()/insert() to re-activate
    // itself and loop fireAllRules() forever, pinning a CPU core in the shared JVM. RuleLogicValidator
    // rejects those keywords at save#Rule, but cap the agenda here as a hard backstop. A legitimate batch
    // fires at most (facts * activeRules) times, far below this; once the cap is hit fireAllRules returns.
    static final int MAX_RULE_FIRES =
            (System.getProperty("darpan.reconciliation.rule.maxRuleFires") ?: "2000000").isInteger() ?
                    (System.getProperty("darpan.reconciliation.rule.maxRuleFires") ?: "2000000").toInteger() : 2_000_000

    // MACH P2 (bound the residual rule-evaluation DoS): MAX_RULE_FIRES caps agenda re-activation
    // loops but not wall-clock — many individually-slow firings can pin a shared-JVM core within a
    // legitimate fire count. A watchdog calls session.halt() after this budget; fireAllRules then
    // returns early and the run FAILS LOUDLY (partial results discarded). Honest scope: halt()
    // interrupts between evaluations — one pathological MVEL evaluation is not interruptible
    // in-process (that tail is the out-of-process sandbox, still deferred). With the DAR-289
    // compile gate rejecting raw tenant DRL by default, this covers the practical residual.
    static final long MAX_RULE_EVAL_MILLIS =
            (System.getProperty("darpan.reconciliation.rule.maxEvalMillis") ?: "60000").isLong() ?
                    (System.getProperty("darpan.reconciliation.rule.maxEvalMillis") ?: "60000").toLong() : 60_000L

    private static final java.util.concurrent.ScheduledExecutorService EVAL_WATCHDOG =
            java.util.concurrent.Executors.newSingleThreadScheduledExecutor({ Runnable r ->
                Thread t = new Thread(r, "darpan-rule-eval-watchdog")
                t.daemon = true
                return t
            } as java.util.concurrent.ThreadFactory)

    /**
     * fireAllRules with a wall-clock budget. Returns [fired, halted, elapsedMillis]; when
     * {@code halted} is true the evaluation was cut off mid-run and results are incomplete —
     * callers must surface an error, never partial output.
     */
    protected static Map<String, Object> fireAllRulesBounded(KieSession session, String ruleSetId,
            long budgetMillis = MAX_RULE_EVAL_MILLIS) {
        java.util.concurrent.atomic.AtomicBoolean halted = new java.util.concurrent.atomic.AtomicBoolean(false)
        java.util.concurrent.ScheduledFuture<?> watchdog = EVAL_WATCHDOG.schedule({
            halted.set(true)
            try {
                session.halt()
                logger.error("Rule evaluation for ruleSet={} exceeded {}ms — session halted", ruleSetId, budgetMillis)
            } catch (Throwable t) {
                logger.warn("Failed to halt over-budget rule session for ruleSet={}: {}", ruleSetId, t.message)
            }
        } as Runnable, budgetMillis, java.util.concurrent.TimeUnit.MILLISECONDS)
        long started = System.currentTimeMillis()
        try {
            int fired = session.fireAllRules(MAX_RULE_FIRES)
            return [fired: fired, halted: halted.get(), elapsedMillis: System.currentTimeMillis() - started]
        } finally {
            watchdog.cancel(false)
        }
    }

    // MACH P0 #5 — the compile path must fail CLOSED on tenant-authored raw DRL. RuleLogicValidator
    // historically gated only save#Rule; a Rule row whose ruleLogic reached the DB by any other path
    // (data load, upgrade-data, a direct entity write, or creation predating the validator) was
    // compiled here unvalidated — an RCE-class residual. Raw `rule … then <arbitrary Java/MVEL> end`
    // blocks are now rejected unless the rule is platform-owned (null companyUserGroupId, loaded by
    // ops via data/*.xml), a server-regenerable FIELD_COMPARISON rule (the UI's only rule type, whose
    // DRL is regenerated server-side), or this property is explicitly enabled for the environment.
    static final String ALLOW_RAW_DRL_PROP = "darpan.rules.allowRawDrl"

    static final ConcurrentMap<String, Map<String, Object>> RULESET_CACHE = boundedRuleSetCache(DEFAULT_RULESET_CACHE_MAX)

    private static boolean rawDrlAllowed() {
        return "true".equalsIgnoreCase(System.getProperty(ALLOW_RAW_DRL_PROP, "false"))
    }

    private static ConcurrentMap<String, Map<String, Object>> boundedRuleSetCache(int maxEntries) {
        // LinkedHashMap with accessOrder=true + custom removeEldestEntry forms an LRU. We wrap in
        // Collections.synchronizedMap to preserve the historic ConcurrentMap type contract callers
        // expect, then expose a ConcurrentMap-compatible adapter. Synchronized is fine here because
        // compileRuleSet runs at rule-edit cadence (low-frequency), not per-row evaluation.
        java.util.LinkedHashMap<String, Map<String, Object>> lru = new java.util.LinkedHashMap<String, Map<String, Object>>(maxEntries, 0.75f, true) {
            @Override
            protected boolean removeEldestEntry(java.util.Map.Entry<String, Map<String, Object>> eldest) {
                if (size() <= maxEntries) return false
                disposeCachedEntry(eldest.value)
                return true
            }
        }
        return new java.util.concurrent.ConcurrentHashMap<String, Map<String, Object>>() {
            @Override Map<String, Object> put(String k, Map<String, Object> v) { synchronized (lru) {
                // Audit 2026-06-11 #7: LinkedHashMap.put on an EXISTING key replaces the value in
                // place and does NOT fire removeEldestEntry, so the displaced KieContainer would
                // leak in Metaspace on every signature-change rebuild. Dispose it here so the
                // dispose path covers in-place replacement, not just capacity eviction.
                Map<String, Object> displaced = lru.put(k, v)
                if (displaced != null && !displaced.is(v) && !displaced.container?.is(v?.container)) disposeCachedEntry(displaced)
                return displaced
            } }
            @Override Map<String, Object> remove(Object k) { synchronized (lru) {
                Map<String, Object> removed = lru.remove(k)
                if (removed != null) disposeCachedEntry(removed)
                return removed
            } }
            @Override Map<String, Object> get(Object k) { synchronized (lru) { return lru.get(k) } }
            @Override int size() { synchronized (lru) { return lru.size() } }
            @Override boolean containsKey(Object k) { synchronized (lru) { return lru.containsKey(k) } }
            @Override void clear() { synchronized (lru) {
                lru.values().each { disposeCachedEntry(it) }
                lru.clear()
            } }
            // No replaceAll / putAll override needed — they delegate to put which synchronizes.
        }
    }

    private static void disposeCachedEntry(Map<String, Object> cached) {
        if (cached == null) return
        Object containerObj = cached.container
        if (containerObj instanceof KieContainer) {
            try {
                (containerObj as KieContainer).dispose()
            } catch (Throwable t) {
                logger.warn("Failed to dispose evicted KieContainer: {}", t.message)
            }
        }
    }

    static String sanitizeIdToken(String raw, String fallbackPrefix) {
        String fallback = normalize(fallbackPrefix)?.toUpperCase(Locale.ROOT)?.replaceAll(/[^A-Z0-9_]/, "_") ?: "ID"
        String cleaned = normalize(raw)?.toUpperCase(Locale.ROOT)?.replaceAll(/[^A-Z0-9_]/, "_")
        cleaned = cleaned?.replaceAll(/_+/, "_")?.replaceAll(/^_+|_+$/, "")
        if (!cleaned) cleaned = fallback
        if (!(cleaned[0] ==~ /[A-Z]/)) cleaned = "${fallback}_${cleaned}"
        if (cleaned.length() > MAX_ID_LENGTH) cleaned = cleaned.substring(0, MAX_ID_LENGTH)
        return cleaned
    }

    static boolean invalidateRuleSetCache(def ec, String ruleSetId) {
        String normalizedRuleSetId = normalize(ruleSetId)
        if (normalizedRuleSetId) {
            RULESET_CACHE.remove(buildCacheKey(normalizedRuleSetId))
            return true
        }
        logger.warn("invalidateRuleSetCache called with no ruleSetId — clearing entire ruleset cache ({} entries across all tenants)", RULESET_CACHE.size())
        RULESET_CACHE.clear()
        return true
    }

    static Map<String, Object> compileRuleSet(def ec, String ruleSetId, boolean useCache, boolean forceRebuild) {
        logger.info("Compiling ruleSet={} useCache={} forceRebuild={}", ruleSetId, useCache, forceRebuild)
        try {
            Map compiled = getOrBuildContainer(ec, ruleSetId, useCache, forceRebuild)
            List warnings = (compiled.warnings ?: []) as List
            return [
                    kieContainer: compiled.container,
                    ruleCount   : compiled.ruleCount,
                    drlText     : compiled.drlText,
                    warnings    : warnings,
                    error       : null
            ]
        } catch (Exception e) {
            logger.error("Failed compiling ruleSet={}", ruleSetId, e)
            return [error: e.message]
        }
    }

    static Map<String, Object> executeRuleSetFacts(def ec, String ruleSetId, List rows, boolean returnAllFacts) {
        try {
            Map compiled = getOrBuildContainer(ec, ruleSetId, true, false)
            KieContainer container = compiled.container as KieContainer
            List warnings = ((compiled.warnings ?: []) as List).collect { it?.toString() }

            List<Map> facts = rows.collect { Object row ->
                if (row instanceof Map) return new LinkedHashMap((Map) row)
                return [value: row]
            }

            List matchedResults = []
            KieSession session = container.newKieSession()
            try {
                session.setGlobal("results", matchedResults)
                facts.each { Map fact -> session.insert(fact) }
                Map<String, Object> fireResult = fireAllRulesBounded(session, ruleSetId)
                if (fireResult.halted) {
                    return [error: "Rule evaluation for ruleSet ${ruleSetId} exceeded ${MAX_RULE_EVAL_MILLIS}ms and was halted; results discarded as incomplete.".toString()]
                }
                int fired = fireResult.fired as int
                List output = returnAllFacts ? facts : matchedResults

                logger.info("Executed ruleSet={} facts={} fired={} returnAllFacts={}", ruleSetId, facts.size(), fired, returnAllFacts)
                return [
                        results       : output,
                        matchedResults: matchedResults,
                        firedRuleCount: fired,
                        ruleCount     : compiled.ruleCount,
                        warnings      : warnings,
                        error         : null
                ]
            } finally {
                disposeQuietly(session)
            }
        } catch (Exception e) {
            logger.error("Rule execution failed for ruleSet={}", ruleSetId, e)
            return [error: "Rule execution failed: ${e.message}"]
        }
    }

    static Map<String, Object> executeMatchedPairFacts(def ec, String ruleSetId, List rows) {
        try {
            Map compiled = getOrBuildContainer(ec, ruleSetId, true, false)
            KieContainer container = compiled.container as KieContainer
            List<String> warnings = ((compiled.warnings ?: []) as List).collect { it?.toString() }.findAll { it }

            List<Map> facts = rows.collect { Object row ->
                (row instanceof Map) ? new LinkedHashMap((Map) row) : [value: row]
            }

            List matchedResults = []
            KieSession session = container.newKieSession()
            try {
                session.setGlobal("results", matchedResults)
                facts.each { Map fact -> session.insert(fact) }
                Map<String, Object> fireResult = fireAllRulesBounded(session, ruleSetId)
                if (fireResult.halted) {
                    return [error: "Rule evaluation for ruleSet ${ruleSetId} exceeded ${MAX_RULE_EVAL_MILLIS}ms and was halted; results discarded as incomplete.".toString()]
                }
                int fired = fireResult.fired as int

                List<Map> diffResults = []
                facts.each { Map fact ->
                    List<Map> normalizedDiffs = RuleDiffSupport.extractNormalizedDiffs(fact)
                    if (normalizedDiffs) {
                        diffResults.addAll(normalizedDiffs)
                        return
                    }

                    List matchedRuleIds = (fact.get("_matchedRuleIds") instanceof List) ? (List) fact.get("_matchedRuleIds") : []
                    if (matchedRuleIds) {
                        String compareScopeId = normalize(fact.compareScopeId)
                        String primaryId = normalize(fact.primaryId)
                        warnings.add("RuleSet ${ruleSetId} matched compareScope=${compareScopeId ?: '(unknown)'} primaryId=${primaryId ?: '(unknown)'} but emitted no diff rows.")
                    }
                }

                logger.info("Executed matched-pair rules ruleSet={} facts={} fired={} diffRows={}",
                        ruleSetId, facts.size(), fired, diffResults.size())
                return [
                        diffResults   : diffResults,
                        matchedResults: matchedResults,
                        firedRuleCount: fired,
                        ruleCount     : compiled.ruleCount,
                        warnings      : warnings.unique(),
                        error         : null
                ]
            } finally {
                disposeQuietly(session)
            }
        } catch (Exception e) {
            logger.error("Matched-pair rule execution failed for ruleSet={}", ruleSetId, e)
            return [error: "Matched-pair rule execution failed: ${e.message}"]
        }
    }

    private static Map<String, Object> getOrBuildContainer(def ec, String ruleSetId, boolean useCache = true, boolean forceRebuild = false) {
        if (!ruleSetId) throw new IllegalArgumentException("ruleSetId is required")

        // P0 #4 step 2 — gate RuleSet by active tenant; fail closed on foreign/missing.
        EntityValue ruleSet = TenantScopedFinder.findTenantScopedById(
                ec, DarpanEntityConstants.RULE_SET, "ruleSetId", ruleSetId)
        if (!ruleSet) throw new IllegalArgumentException("RuleSet ${ruleSetId} not found or access denied")

        List rules = fetchActiveRules(ec, ruleSetId)
        if (!rules) throw new IllegalArgumentException("RuleSet ${ruleSetId} has no active rules")

        // Audit 2026-06-11 #27: the tenant is taken from the RuleSet itself, not from the
        // never-populated ec.context.tenantId. ruleSetId is a globally unique PK, so it alone is a
        // collision-free cache key; the tenant token is used only for the DRL package namespace and
        // is invariant across interactive and automation/system execution of the same ruleset.
        String tenantId = resolveTenantToken(ruleSet)
        String signature = makeRuleSignature(ruleSet, rules)
        String cacheKey = buildCacheKey(ruleSetId)

        Map cached = RULESET_CACHE[cacheKey]
        if (!forceRebuild && useCache && cached != null && signature == cached.signature && cached.container != null) {
            return [
                    container: cached.container,
                    drlText  : cached.drlText,
                    ruleCount: cached.ruleCount,
                    warnings : new ArrayList((List) (cached.warnings ?: []))
            ]
        }

        List<String> warnings = []
        String sanitizedRuleSetId = sanitizePackagePart(ruleSetId)
        String packageName = "reconciliation.rules.${sanitizePackagePart(tenantId)}.${sanitizedRuleSetId}"
        String drlText = buildRuleSetDrl(ruleSetId, packageName, rules, warnings, normalize(ruleSet?.companyUserGroupId))

        // Drools 8.x's EvaluatorRegistry registers temporal evaluators using the ACTIVE thread-context
        // classloader during buildAll(); under Moqui's component MClassLoader the evaluator classes would
        // otherwise split (AfterEvaluatorDefinition via MClassLoader vs EvaluatorDefinition via the app
        // loader) and throw a ClassCastException. Pin the TCCL to the loader that loaded this component
        // (which carries the Drools 8.x jars) so all Drools classes resolve from one loader, and pass the
        // same loader to the KieContainer. (Drools 7.x did not trip this; required by the 8.x bump.)
        ClassLoader drlClassLoader = RuleEngineSupport.class.getClassLoader()
        ClassLoader prevTccl = Thread.currentThread().getContextClassLoader()
        KieContainer container
        try {
            Thread.currentThread().setContextClassLoader(drlClassLoader)

            KieServices ks = KieServices.Factory.get()
            KieFileSystem kfs = ks.newKieFileSystem()
            String drlPath = "src/main/resources/${packageName.replace('.', '/')}/${sanitizedRuleSetId}.drl"
            kfs.write(drlPath, drlText)

            KieBuilder kb = ks.newKieBuilder(kfs)
            kb.buildAll()

            if (kb.getResults().hasMessages(Message.Level.ERROR)) {
                List<String> errors = (kb.getResults().getMessages(Message.Level.ERROR) ?: [])
                        .collect { Message m -> m?.text ?: m?.toString() }
                        .findAll { it }
                String errSummary = errors ? errors.join(" | ") : kb.getResults().toString()
                throw new IllegalArgumentException("Drools build errors for ${ruleSetId}: ${errSummary}")
            }

            container = ks.newKieContainer(kb.getKieModule().getReleaseId(), drlClassLoader)
        } finally {
            Thread.currentThread().setContextClassLoader(prevTccl)
        }
        Map entry = [
                signature: signature,
                drlText  : drlText,
                ruleCount: rules.size(),
                warnings : new ArrayList(warnings),
                container: container
        ]
        RULESET_CACHE[cacheKey] = entry

        return [
                container: container,
                drlText  : drlText,
                ruleCount: rules.size(),
                warnings : warnings
        ]
    }

    private static List fetchActiveRules(def ec, String ruleSetId) {
        // P0 #4 step 2 — gate via parent RuleSet; fail closed if parent is foreign/missing.
        def childFinder = TenantScopedFinder.findTenantScopedChildren(
                ec, "darpan.rule.Rule", DarpanEntityConstants.RULE_SET, "ruleSetId", ruleSetId, "ruleSetId")
        if (childFinder == null) return []
        return (childFinder.condition("enabled", "Y")
                .orderBy(["sequenceNum", "ruleId"])
                .useCache(false)
                .list() ?: []) as List
    }

    private static String makeRuleSignature(EntityValue ruleSet, List rules) {
        String ruleSetStamp = [
                normalize(ruleSet?.ruleSetId),
                normalize(ruleSet?.ruleSetName),
                normalize(ruleSet?.version),
                normalize(ruleSet?.lastUpdatedDate)
        ].join("|")
        String ruleStamp = rules.collect { rule ->
            [
                    normalize(rule.ruleId),
                    normalize(rule.sequenceNum),
                    normalize(rule.enabled),
                    normalize(rule.ruleText),
                    normalize(rule.ruleLogic),
                    normalize(rule.lastUpdatedDate)
            ].join("|")
        }.join("||")
        // Hash to a fixed-width token so cache equality checks are O(1) regardless of
        // ruleset size, and so signature storage in RULESET_CACHE doesn't grow with rule content.
        return sha256("${ruleSetStamp}@@${ruleStamp}")
    }

    private static String sha256(String raw) {
        byte[] hash = MessageDigest.getInstance("SHA-256").digest((raw ?: "").getBytes("UTF-8"))
        return hash.encodeHex().toString()
    }

    /**
     * Compile-time fail-closed gate (MACH P0 #5). Throws IllegalArgumentException when {@code ruleLogic}
     * must not be handed to the Drools compiler:
     *   (1) it fails {@link RuleLogicValidator} — re-checked HERE, not only at save#Rule, so a row that
     *       reached the DB by any other path (data load, upgrade-data, a direct entity write, or creation
     *       predating the validator) cannot be compiled unvalidated; or
     *   (2) it is a raw {@code rule … end} block AND the rule is neither platform-owned (null
     *       companyUserGroupId, loaded by ops) nor a server-regenerable FIELD_COMPARISON rule, and
     *       {@code darpan.rules.allowRawDrl} is not enabled.
     * Legitimate rules (the FieldComparisonRuleLogicGenerator output and every platform seed rule in
     * data/*.xml) already satisfy the allow-list, so this rejects only unsanctioned tenant DRL.
     */
    static void assertCompilableRuleLogic(String ruleName, String ruleLogic, String ruleType,
                                          String expression, String companyUserGroupId) {
        String logic = normalize(ruleLogic)
        if (!logic) return

        // (1) Belt-and-braces: the same allow-list that gates save#Rule, re-applied at compile time.
        String violation = RuleLogicValidator.firstViolation(logic)
        if (violation) {
            throw new IllegalArgumentException("Rule ${ruleName} rejected at compile time: ${violation}")
        }

        // (2) Default-OFF raw-DRL gate.
        String trimmed = logic.trim()
        boolean isRawBlock = trimmed.toLowerCase(Locale.ROOT).startsWith("rule ") || trimmed.contains("\nrule ")
        if (!isRawBlock) return

        boolean platformRule = !normalize(companyUserGroupId)
        boolean regenerableFieldComparison =
                normalize(ruleType) == FieldComparisonRuleLogicGenerator.FIELD_COMPARISON_TYPE && normalize(expression)
        if (platformRule || regenerableFieldComparison || rawDrlAllowed()) return

        throw new IllegalArgumentException(
                "Rule ${ruleName} supplies a raw DRL block. Tenant-authored raw DRL is disabled in this " +
                "environment; express the rule as a structured field comparison instead " +
                "(set ${ALLOW_RAW_DRL_PROP}=true to override).")
    }

    // Package-visible (not private) so the compile-time fail-closed gate can be exercised directly by
    // RuleEngineSupportCompileGateTests without booting a full Moqui/DB context.
    static String buildRuleSetDrl(String ruleSetId, String packageName, List rules, List<String> warnings,
                                  String companyUserGroupId) {
        // Audit 2026-06-11 #1: do NOT hoist author-declared imports into the DRL header. Custom
        // imports were an arbitrary-class injection vector; RuleLogicValidator rejects imports at
        // save#Rule, and stripDrlHeaders drops any import lines inside raw blocks. Legitimate rule
        // logic (UI-generated and platform rules) references helpers by fully-qualified name and
        // needs only the fixed standard header below.
        StringBuilder drl = new StringBuilder()
        drl.append("package ${packageName}\n")
        drl.append("import java.util.Map\n")
        drl.append("import java.util.List\n")
        drl.append("import java.util.ArrayList\n")
        drl.append("import java.util.Objects\n")
        drl.append("import reconciliation.rule.RuleDiffSupport\n")
        drl.append("global java.util.List results\n\n")

        int generatedRules = 0
        boolean hasRawBlocks = false
        boolean hasParsedRules = false

        rules.eachWithIndex { rule, idx ->
            String ruleName = normalize(rule.ruleId) ?: "RULE_${idx + 1}"
            String ruleLogic = normalize(rule.ruleLogic)
            String ruleText = normalize(rule.ruleText)
            int salience = 10000 - idx

            // MACH P0 #5 — fail closed before any tenant ruleLogic reaches the Drools/MVEL/ECJ compiler.
            assertCompilableRuleLogic(ruleName, ruleLogic, normalize(rule.ruleType),
                    normalize(rule.expression), companyUserGroupId)

            if (ruleLogic) {
                String trimmed = ruleLogic.trim()
                if (trimmed.toLowerCase().startsWith("rule ") || trimmed.contains("\nrule ")) {
                    String normalizedBlock = stripDrlHeaders(trimmed)
                    if (normalizedBlock && normalizedBlock.toLowerCase().contains("rule ")) {
                        drl.append(normalizedBlock).append("\n\n")
                        generatedRules++
                        hasRawBlocks = true
                    } else {
                        warnings.add("Rule ${ruleName} DRL block had no executable rule after header cleanup.")
                    }
                } else {
                    drl.append(buildRuleBlock(ruleName, trimmed, salience)).append("\n")
                    generatedRules++
                }
                return
            }

            if (!ruleText) {
                warnings.add("Rule ${ruleName} has no ruleLogic or ruleText and was skipped.")
                return
            }

            String parsed = parseCondition(ruleText)
            if (!parsed) {
                warnings.add("Rule ${ruleName} ruleText could not be parsed and was skipped: ${ruleText}")
                return
            }
            drl.append(buildRuleBlock(ruleName, parsed, salience)).append("\n")
            generatedRules++
            hasParsedRules = true
        }

        if (hasRawBlocks && hasParsedRules) {
            warnings.add("RuleSet ${ruleSetId} mixes raw DRL blocks (author-defined salience) and parsed ruleText rules (sequence-based salience). Verify that execution ordering across both rule types is intentional.")
        }

        if (generatedRules == 0) {
            throw new IllegalArgumentException("RuleSet ${ruleSetId} has no executable active rules")
        }
        return drl.toString()
    }

    private static String buildRuleBlock(String ruleName, String condition, int salience) {
        String safeRuleName = sanitizeRuleName(ruleName)
        return """
rule "${safeRuleName}"
    salience ${salience}
when
    \$m : Map(${condition})
then
    List _matchedRuleIds = (List) \$m.get("_matchedRuleIds");
    if (_matchedRuleIds == null) {
        _matchedRuleIds = new ArrayList();
        \$m.put("_matchedRuleIds", _matchedRuleIds);
    }
    if (!_matchedRuleIds.contains("${safeRuleName}")) _matchedRuleIds.add("${safeRuleName}");
    if (!results.contains(\$m)) results.add(\$m);
end
"""
    }

    private static String stripDrlHeaders(String drlText) {
        if (!drlText) return ""
        return drlText.readLines().findAll { String line ->
            String trimmed = line?.trim()?.toLowerCase()
            return !(trimmed?.startsWith("package ") || trimmed?.startsWith("import ") || trimmed?.startsWith("global "))
        }.join("\n").trim()
    }

    private static String sanitizeRuleName(String raw) {
        return sanitizeDisplayName(raw, "Unnamed Rule")
    }

    private static String sanitizePackagePart(String raw) {
        String cleaned = normalize(raw)?.toLowerCase()?.replaceAll(/[^a-z0-9_]/, "_")?.replaceAll(/_+/, "_")
        if (!cleaned) cleaned = "default_ruleset"
        if (!(cleaned[0] ==~ /[a-z_]/)) cleaned = "rs_${cleaned}"
        if (JAVA_KEYWORDS.contains(cleaned)) cleaned = "rs_${cleaned}"
        return cleaned
    }

    private static String resolveTenantToken(EntityValue ruleSet) {
        String tenantId = normalize(ruleSet?.companyUserGroupId)
        return sanitizeIdToken(tenantId ?: "DEFAULT", "TENANT")
    }

    private static String buildCacheKey(String ruleSetId) {
        return normalize(ruleSetId)
    }

    private static void disposeQuietly(KieSession session) {
        try {
            session?.dispose()
        } catch (Exception ignored) {
            // Best effort cleanup; the service response should preserve the original rule result.
        }
    }
}
