package reconciliation.rule

import darpan.reconciliation.support.ReconciliationSmokeTestSupport
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.moqui.context.ExecutionContext

import java.nio.file.Path

import static org.junit.jupiter.api.Assertions.assertEquals
import static org.junit.jupiter.api.Assertions.assertFalse
import static org.junit.jupiter.api.Assertions.assertNotNull
import static org.junit.jupiter.api.Assertions.assertTrue

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class RuleEngineServiceSmokeTests {
    private ExecutionContext ec

    @BeforeAll
    void setup() {
        Path backendRoot = ReconciliationSmokeTestSupport.resolveBackendRoot()
        ec = ReconciliationSmokeTestSupport.initMoqui(backendRoot, "rule-engine-service-smoke")
        ReconciliationSmokeTestSupport.seedBaseCompareRuleSet(ec)
    }

    @AfterAll
    void cleanup() {
        ReconciliationSmokeTestSupport.cleanupMoqui(ec)
    }

    @BeforeEach
    void clearErrors() {
        ec.message.clearErrors()
    }

    @Test
    void xmlBackedRuleSetSaveUsesMoquiPrimaryIdForCreate() {
        Map<String, Object> created = ec.service.sync()
                .name("reconciliation.ReconciliationRuleEngineServices.save#RuleSet")
                .parameters([
                        ruleSetName: "Generated RuleSet",
                        description: "Generated by Moqui entity-auto create"
                ])
                .disableAuthz()
                .call()

        assertFalse(ec.message.hasError())
        assertNotNull(created.ruleSetId)
        assertTrue((Boolean) created.created)
        assertFalse((Boolean) created.updated)

        Object ruleSetRow = ec.entity.find("darpan.rule.RuleSet")
                .condition("ruleSetId", created.ruleSetId)
                .disableAuthz()
                .useCache(false)
                .one()
        assertEquals("Generated RuleSet", ruleSetRow.ruleSetName)

        Map<String, Object> updated = ec.service.sync()
                .name("reconciliation.ReconciliationRuleEngineServices.save#RuleSet")
                .parameters([
                        ruleSetId  : created.ruleSetId,
                        ruleSetName: "Updated Generated RuleSet"
                ])
                .disableAuthz()
                .call()

        assertFalse(ec.message.hasError())
        assertEquals(created.ruleSetId, updated.ruleSetId)
        assertFalse((Boolean) updated.created)
        assertTrue((Boolean) updated.updated)
    }

    @Test
    void xmlBackedRuleSetSaveRejectsInvalidIds() {
        ec.service.sync()
                .name("reconciliation.ReconciliationRuleEngineServices.save#RuleSet")
                .parameters([
                        ruleSetId  : "RS BAD!",
                        ruleSetName: "Invalid RuleSet"
                ])
                .disableAuthz()
                .call()

        assertTrue(ec.message.hasError())
        assertTrue(ec.message.errorsString.contains("ruleSetId contains invalid characters: RS BAD!"))
    }

    @Test
    void xmlBackedRuleSaveCreatesUpdatesAndCompilesRule() {
        Map<String, Object> created = ec.service.sync()
                .name("reconciliation.ReconciliationRuleEngineServices.save#Rule")
                .parameters([
                        ruleSetId     : "DARPAN_TEST_COMPARE_RS",
                        ruleText      : "status is Pending",
                        severity      : "WARN",
                        validateOnSave: true
                ])
                .disableAuthz()
                .call()

        assertFalse(ec.message.hasError())
        assertEquals("DARPAN_TEST_COMPARE_RS", created.ruleSetId)
        assertEquals(10L, ((Number) created.sequenceNum).longValue())
        assertTrue(((List) (created.warnings ?: [])).isEmpty())

        String ruleId = created.ruleId as String
        assertNotNull(ruleId)

        Object ruleRow = ec.entity.find("darpan.rule.Rule")
                .condition("ruleId", ruleId)
                .disableAuthz()
                .useCache(false)
                .one()
        assertEquals("Y", ruleRow.enabled)
        assertEquals("status is Pending", ruleRow.ruleText)

        Map<String, Object> updated = ec.service.sync()
                .name("reconciliation.ReconciliationRuleEngineServices.save#Rule")
                .parameters([
                        ruleSetId: "DARPAN_TEST_COMPARE_RS",
                        ruleId   : ruleId,
                        ruleText : "status is Shipped",
                        enabled  : false
                ])
                .disableAuthz()
                .call()

        assertFalse(ec.message.hasError())
        assertEquals(ruleId, updated.ruleId)
        assertEquals(10L, ((Number) updated.sequenceNum).longValue())

        ruleRow = ec.entity.find("darpan.rule.Rule")
                .condition("ruleId", ruleId)
                .disableAuthz()
                .useCache(false)
                .one()
        assertEquals("N", ruleRow.enabled)
        assertEquals("status is Shipped", ruleRow.ruleText)
    }
}
